import type { Framework, FrameworkAdapter, BuildContext, BuildResult } from './types.js';
import type { StitchMcpClient } from '../mcp/client.js';

export class AstroAdapter implements FrameworkAdapter {
  readonly name: Framework = 'astro';
  private client: StitchMcpClient;

  constructor(client: StitchMcpClient) {
    this.client = client;
  }

  async build(context: BuildContext): Promise<BuildResult> {
    const { projectId, screens } = context;

    const routes = screens.map((screen) => ({
      screenId: screen.screenId,
      route: screen.route,
    }));

    const result = await this.client.buildSite(projectId, routes);

    const files = result.pages.map((page) => page.route);

    return {
      files,
      instructions: [
        'Your Astro site has been generated by Stitch.',
        'Follow the Stitch build output instructions to preview and deploy.',
      ],
    };
  }
}
