import { writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import * as cheerio from 'cheerio';
import { getForgeSignature, type Framework, type FrameworkAdapter, type BuildContext, type BuildResult } from './types.js';

export class NextjsAdapter implements FrameworkAdapter {
  readonly name: Framework = 'nextjs';

  async build(context: BuildContext): Promise<BuildResult> {
    const { outputDir, screens } = context;
    const files: string[] = [];

    // Create package.json
    const packageJsonPath = join(outputDir, 'package.json');
    mkdirSync(outputDir, { recursive: true });
    writeFileSync(packageJsonPath, JSON.stringify({
      name: 'stitch-forge-site',
      version: '0.2.0',
      private: true,
      scripts: {
        dev: 'next dev',
        build: 'next build',
        start: 'next start',
      },
      dependencies: {
        next: '^14.2.0',
        react: '^18.3.1',
        'react-dom': '^18.3.1',
      },
    }, null, 2) + '\n');
    files.push(packageJsonPath);

    // Create next.config.js
    const nextConfigPath = join(outputDir, 'next.config.js');
    writeFileSync(nextConfigPath, `/** @type {import('next').NextConfig} */\nconst nextConfig = {\n  output: 'export',\n};\n\nmodule.exports = nextConfig;\n`);
    files.push(nextConfigPath);

    // Create tsconfig.json
    const tsconfigPath = join(outputDir, 'tsconfig.json');
    writeFileSync(tsconfigPath, JSON.stringify({
      compilerOptions: {
        target: 'es5',
        lib: ['dom', 'dom.iterable', 'esnext'],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: 'esnext',
        moduleResolution: 'bundler',
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: 'preserve',
        incremental: true,
        plugins: [{ name: 'next' }],
        paths: { '@/*': ['./*'] },
      },
      include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
      exclude: ['node_modules'],
    }, null, 2) + '\n');
    files.push(tsconfigPath);

    // Create app directory
    const appDir = join(outputDir, 'app');
    mkdirSync(appDir, { recursive: true });

    // Create globals.css
    const globalsCssPath = join(appDir, 'globals.css');
    writeFileSync(globalsCssPath, '/* Global styles placeholder */\n');
    files.push(globalsCssPath);

    // Create root layout
    const layoutPath = join(appDir, 'layout.tsx');
    writeFileSync(layoutPath, `import './globals.css';

export const metadata = {
  title: 'Stitch Forge Site',
  description: 'Generated by Stitch Forge',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`);
    files.push(layoutPath);

    // Create pages for each screen
    for (const screen of screens) {
      const pagePath = this.routeToPagePath(appDir, screen.route);
      const pageDir = pagePath.substring(0, pagePath.lastIndexOf('/'));
      mkdirSync(pageDir, { recursive: true });

      const $ = cheerio.load(screen.html);
      const title = $('title').text() || screen.name;
      const bodyContent = $('body').html() || screen.html;

      // Extract inline styles from <head> if any
      const styles: string[] = [];
      $('style').each((_, el) => {
        styles.push($(el).html() || '');
      });

      const styleTag = styles.length > 0
        ? `\n      <style dangerouslySetInnerHTML={{ __html: \`${styles.join('\n')}\` }} />`
        : '';

      const forgeComment = getForgeSignature().replace('<!--', '{/*').replace('-->', '*/}');
      const pageContent = `${forgeComment}import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: ${JSON.stringify(title)},
};

export default function Page() {
  return (
    <>
      <div dangerouslySetInnerHTML={{ __html: \`${this.escapeTemplateLiteral(bodyContent)}\` }} />${styleTag}
    </>
  );
}
`;
      writeFileSync(pagePath, pageContent);
      files.push(pagePath);
    }

    return {
      files,
      instructions: [`cd ${outputDir} && npm install && npx next dev`],
    };
  }

  private routeToPagePath(appDir: string, route: string): string {
    if (route === '/') {
      return join(appDir, 'page.tsx');
    }
    const cleanRoute = route.replace(/^\//, '');
    return join(appDir, cleanRoute, 'page.tsx');
  }

  private escapeTemplateLiteral(str: string): string {
    return str.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
  }
}
